#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Th3Mouk\OpenAPIGenerator\Command\GenerateCommand;
use Th3Mouk\OpenAPIGenerator\Command\ScaffoldCommand;

set_time_limit(0);

if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

$input = new ArgvInput();

$application = new Application();

$application->add(new GenerateCommand());
$application->add(new ScaffoldCommand());

$application->run($input);
